name: ClicketProd
channels:
  - conda-forge
dependencies:
  - apscheduler
  - fastapi
  - numpy
  - python=3.11
  - scipy
  - uvicorn
  - gunicorn
  - websockets
  - sqlite
  - sqlalchemy
  - filelock
  - argon2-cffi
  - pip
  - pip:
    - dotenv
