import { useState, useEffect } from "react";
import './TeamsList.css';
import uk from "../assets/labeled-team-map-2.svg"
import imageMapResize  from "image-map-resizer";

export default function TeamList() {
  const [teamData, setTeamData] = useState(null);

  useEffect(() => {
    imageMapResize();
  }, []);

  return (
    <div style={{ padding: "1rem" }}>
      <h1>Teams</h1>
      <div style={{display:"flex", flexDirection:"row"}}>
        {/* <ul>
          <li><a className='team-link' href='/team/1' style={{color:"#B00060"}}>Nottingham Nightingales</a></li>
          <li><a className='team-link' href='/team/2' style={{color:"#00B050"}}>Birmingham Bullfrogs</a></li>
          <li><a className='team-link' href='/team/3' style={{color:"#E97132"}}>Cornwall Catastrophes</a></li>
          <li><a className='team-link' href='/team/4' style={{color:"#FE01B7"}}>Brighton Beachcombers</a></li>
          <li><a className='team-link' href='/team/5' style={{color:"#0055FF"}}>Manchester Monsters</a></li>
          <li><a className='team-link' href='/team/6' style={{color:"#EF000E"}}>Cardiff Cwtchers</a></li>
          <li><a className='team-link' href='/team/7' style={{color:"#00EFE1"}}>Bristol Bats</a></li>
          <li><a className='team-link' href='/team/8' style={{color:"#32AA39"}}>Devon Devils</a></li>
          <li><a className='team-link' href='/team/9' style={{color:"#01FE48"}}>Parliamentary Penpushers</a></li>
          <li><a className='team-link' href='/team/10' style={{color:"#7BD23C"}}>Glasgow Goofballs</a></li>
          <li><a className='team-link' href='/team/11' style={{color:"#933CD2"}}>Edinburgh XI</a></li>
          <li><a className='team-link' href='/team/12' style={{color:"#DCAE00"}}>Yorkshire Puddings</a></li>
        </ul> */}
         {/* Image Map Generated by http://www.image-map.net/  */}
        <img src={uk} usemap="#image-map" style={{ maxWidth: "90%", height: "auto" }}/>

        <map name="image-map">
          <area target="" alt="Lincoln Lightning" title="Lincoln Lightning" href="/team/1" coords="3076,1304,3073,1439,2398,1439,2398,1376,2006,1412,1990,1436,1957,1439,1930,1427,1939,1394,1960,1370,1994,1382,2009,1394,2395,1358,2395,1301" shape="poly" />
          <area target="" alt="Birmingham Bullfrogs" title="Birmingham Bullfrogs" href="/team/2" coords="106,1249,941,1249,947,1310,1743,1521,1770,1515,1810,1536,1804,1572,1773,1584,1746,1566,1734,1542,947,1328,944,1382,106,1382" shape="poly" />
          <area target="" alt="Cornwall Catastrophes" title="Cornwall Catastrophes" href="/team/3" coords="21,2046,920,2040,920,2106,1258,1961,1279,1940,1309,1940,1321,1964,1315,1992,1285,1995,1267,1982,917,2127,920,2182,18,2182" shape="poly" />
          <area target="" alt="Brighton Beachcombers" title="Brighton Beachcombers" href="/team/4" coords="2223,2067,2663,2073,2054,1883,2024,1901,1997,1859,2018,1820,2051,1823,2066,1862,2702,2076,2850,2070,3164,2070,3158,2209,2223,2209" shape="poly" />
          <area target="" alt="Manchester Monsters" title="Manchester Monsters" href="/team/5" coords="220,866,1068,869,1065,990,1698,1337,1734,1337,1758,1361,1731,1394,1698,1385,1686,1352,1047,999,214,1002" shape="poly" />
          <area target="" alt="Cardiff Cwtchers" title="Cardiff Cwtchers" href="/team/6" coords="296,1581,974,1581,971,1639,1544,1723,1571,1699,1601,1705,1607,1744,1586,1768,1556,1747,1526,1735,974,1666,971,1714,299,1717" shape="poly" />
          <area target="" alt="Bristol Bats" title="Bristol Bats" href="/team/7" coords="642,1807,1122,1807,1119,1859,1635,1750,1632,1711,1671,1708,1698,1726,1686,1768,1656,1771,1623,1765,1119,1892,1119,1940,639,1946" shape="poly" />
          <area target="" alt="Devon Devils" title="Devon Devils" href="/team/8" coords="1439,2082,1698,2079,1538,1910,1496,1904,1487,1874,1502,1850,1535,1844,1562,1859,1553,1892,1719,2076,1972,2079,1975,2218,1442,2212" shape="poly" />
          <area target="" alt="Parliamentary Penpushers" title="Parliamentary Penpushers" href="/team/9" coords="2370,1648,3411,1651,3411,1786,2374,1789,2380,1723,2060,1738,2036,1768,2003,1756,2000,1717,2012,1690,2051,1702,2069,1720,2380,1702" shape="poly" />
          <area target="" alt="Glasgow Goofballs" title="Glasgow Goofballs" href="/team/10" coords="184,450,926,447,923,573,1420,893,1454,881,1472,911,1472,935,1445,951,1420,947,1411,926,1405,905,908,588,184,585,184,504" shape="poly" />
          <area target="" alt="Edinburgh XI" title="Edinburgh XI" href="/team/11" coords="2108,513,2660,516,2660,652,2120,658,1623,890,1623,917,1601,932,1565,926,1553,896,1574,863,1604,866,1623,872,2114,628" shape="poly" />
          <area target="" alt="Yorkshire Puddings" title="Yorkshire Puddings" href="/team/12" coords="2443,911,3218,911,3218,1047,2443,1047,2443,990,1852,1282,1861,1301,1846,1322,1819,1337,1800,1325,1791,1295,1810,1273,1837,1270,2446,966" shape="poly" />
        </map>
      </div>
    </div>
  )
}