import { useState, useEffect } from "react";
import './TeamsList.css';
import uk from "../assets/labeled-team-map.svg"
import imageMapResize  from "image-map-resizer";

export default function TeamList() {
  const [teamData, setTeamData] = useState(null);

  useEffect(() => {
    imageMapResize();
  }, []);

  return (
    <div style={{ padding: "1rem" }}>
      <h1>Teams</h1>
      <div style={{display:"flex", flexDirection:"row"}}>
        {/* <ul>
          <li><a className='team-link' href='/team/1' style={{color:"#B00060"}}>Nottingham Nightingales</a></li>
          <li><a className='team-link' href='/team/2' style={{color:"#00B050"}}>Birmingham Bullfrogs</a></li>
          <li><a className='team-link' href='/team/3' style={{color:"#E97132"}}>Cornwall Catastrophes</a></li>
          <li><a className='team-link' href='/team/4' style={{color:"#FE01B7"}}>Brighton Beachcombers</a></li>
          <li><a className='team-link' href='/team/5' style={{color:"#0055FF"}}>Manchester Monsters</a></li>
          <li><a className='team-link' href='/team/6' style={{color:"#EF000E"}}>Cardiff Cwtchers</a></li>
          <li><a className='team-link' href='/team/7' style={{color:"#00EFE1"}}>Bristol Bats</a></li>
          <li><a className='team-link' href='/team/8' style={{color:"#32AA39"}}>Devon Devils</a></li>
          <li><a className='team-link' href='/team/9' style={{color:"#01FE48"}}>Parliamentary Penpushers</a></li>
          <li><a className='team-link' href='/team/10' style={{color:"#7BD23C"}}>Glasgow Goofballs</a></li>
          <li><a className='team-link' href='/team/11' style={{color:"#933CD2"}}>Edinburgh XI</a></li>
          <li><a className='team-link' href='/team/12' style={{color:"#DCAE00"}}>Yorkshire Puddings</a></li>
        </ul> */}
         {/* Image Map Generated by http://www.image-map.net/  */}
        <img src={uk} usemap="#image-map" style={{ maxWidth: "100%", height: "auto" }}/>

        <map name="image-map">
          <area target="" alt="Nottingham Nightingales" title="Nottingham Nightingales" href="/team/1" coords="2394,1298,3354,1307,3360,1439,2394,1436,2394,1379,1899,1448,1899,1478,1872,1490,1845,1460,1851,1430,1890,1421,1911,1427,2400,1358" shape="poly" />
          <area target="" alt="Birmingham Bullfrogs" title="Birmingham Bullfrogs" href="/team/2" coords="99,1250,948,1247,942,1304,1737,1523,1770,1511,1797,1544,1794,1574,1758,1577,1734,1544,939,1334,948,1391,102,1388,96,1250" shape="poly" />
          <area target="" alt="Cornwall Catastrophes" title="Cornwall Catastrophes" href="/team/3" coords="21,2045,915,2048,942,2054,1254,1967,1260,1940,1296,1928,1332,1964,1305,1988,1269,2000,915,2078,918,2183,21,2174" shape="poly" />
          <area target="" alt="Brighton Beachcombers" title="Brighton Beachcombers" href="/team/4" coords="2220,2066,2421,2069,2052,1883,2028,1892,2004,1868,2001,1835,2031,1820,2058,1844,2061,1862,2460,2072,3159,2069,3162,2204,2223,2204" shape="poly" />
          <area target="" alt="Manchester Monsters" title="Manchester Monsters" href="/team/5" coords="216,867,1065,864,1065,930,1689,1331,1722,1319,1743,1346,1743,1364,1728,1385,1695,1382,1683,1355,1065,951,1071,1008,216,1002" shape="poly" />
          <area target="" alt="Cardiff Cwtchers" title="Cardiff Cwtchers" href="/team/6" coords="297,1580,972,1580,972,1640,1539,1709,1575,1703,1599,1712,1605,1733,1581,1757,1557,1748,1533,1733,978,1664,975,1715,297,1718" shape="poly" />
          <area target="" alt="Bristol Bats" title="Bristol Bats" href="/team/7" coords="375,1787,855,1784,849,1844,1626,1742,1647,1700,1686,1706,1692,1739,1674,1757,1635,1772,1617,1763,849,1868,855,1925,366,1925" shape="poly" />
          <area target="" alt="Devon Devils" title="Devon Devils" href="/team/8" coords="1437,2078,1755,2081,1545,1913,1503,1910,1485,1868,1512,1838,1545,1856,1548,1883,1785,2078,1971,2072,1974,2210,1440,2213" shape="poly" />
          <area target="" alt="Parliamentary Penpushers" title="Parliamentary Penpushers" href="/team/9" coords="2373,1658,3384,1652,3390,1781,2373,1787,2379,1736,2064,1748,2022,1766,1998,1751,1995,1721,1998,1694,2028,1691,2064,1715,2379,1700" shape="poly" />
          <area target="" alt="Glasgow Goofballs" title="Glasgow Goofballs" href="/team/10" coords="183,456,927,450,930,585,885,585,1407,885,1458,882,1467,918,1449,948,1419,942,1401,906,861,591,180,588" shape="poly" />
          <area target="" alt="Edinburgh XI" title="Edinburgh XI" href="/team/11" coords="2106,513,2631,516,2628,651,2265,657,1620,894,1614,924,1572,930,1551,909,1554,870,1587,864,1611,873,2235,648,2109,654" shape="poly" />
          <area target="" alt="Yorkshire Puddings" title="Yorkshire Puddings" href="/team/12" coords="2442,909,3192,912,3192,1044,2481,1047,1842,1283,1851,1316,1809,1331,1782,1304,1803,1262,1827,1268,2448,1047,2442,978" shape="poly" />
        </map>
      </div>
    </div>
  )
}